### ISSUE TITLE
Reporting a Missing EQ Translation

### ISSUE THREAD

**Issue by Luarst** [Kxze/PSO2-EQ-API#2]
Deus ESC-A isn't on here. Here is the Japanese text for convinence. 
新世を成す幻創の造神

**Comment by Kxze** [comment]
Thanks! Fixed on Kxze/PSO2-EQ-API@1b7c60a4e017b536d89578d2e0b47f943d02317e.

**Comment by Luarst** [comment]
Your discord bot uses this, right? Beach Wars shows as untranslated as well because of the 2017 at the end.
ビーチウォーズ２０１７！

**Comment by Kxze** [comment]
Hmm, that's an interesting idea. I'll definitely consider it, though I'm not sure how feasible it'd be, since that'd involve making a separate call to the API for every server the bot is in, and not only would that cause a lot of overhead, it would delay the alerts themselves. Let me know if you have any other ideas.

Beach Wars! 2017 added on b67202a4946d4700465f71ea5d6c1edd6e18093c

**Comment by Luarst** [comment]
I put in my own spaghetti code for this, that way I wouldn't have to wait for site updates.. (Well I copied the way the API translates.) AND IT WORKS! Thanks for this wonderful bot.

**Comment by Kxze** [comment]
No problem fam o/
